language: ruby
sudo: false
cache: bundler
before_install: gem install bundler
bundler_args: --without guard
script: "bundle exec rake spec"
rvm:
  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - rbx-2
  - jruby
  - ruby-head
  - jruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
